(()=>{
'use strict';
const Cloud=window.NovaCloud;
function esc(v=''){return String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]))}
function status(text,type='info'){let el=document.getElementById('cloudStatus');if(!el)return;el.textContent=text;el.dataset.type=type}
function panel(){const box=document.querySelector('.setup-box');if(!box||document.getElementById('cloudSetup'))return;const s=Cloud.readSettings();box.insertAdjacentHTML('afterbegin',`<section id="cloudSetup" class="cloud-setup"><div class="cloud-head"><div><span class="muted">قاعدة البيانات السحابية</span><h3>ربط Supabase</h3></div><span class="status-chip ${Cloud.configured()?'on':'off'}">${Cloud.configured()?'متصل بالإعدادات':'غير مربوط'}</span></div><div class="cloud-fields"><label class="field full"><span>رابط المشروع</span><input id="supabaseUrl" type="url" placeholder="https://xxxxx.supabase.co" value="${esc(s.supabaseUrl||'')}"></label><label class="field full"><span>المفتاح العام Anon / Publishable</span><input id="supabaseKey" type="password" placeholder="eyJ..." value="${esc(s.supabaseAnonKey||'')}"></label><label class="check-field"><input id="autoSync" type="checkbox" ${s.autoSync!==false?'checked':''}> مزامنة تلقائية عند فتح التطبيق</label></div><div class="form-actions cloud-actions"><button class="action-btn primary" onclick="saveCloudSettings()">حفظ واختبار</button><button class="action-btn" onclick="pullCloudData()">تنزيل من السحابة</button><button class="action-btn" onclick="pushCloudData()">رفع البيانات الحالية</button><button class="action-btn danger" onclick="disableCloud()">العودة للوضع المحلي</button></div><div id="cloudStatus" class="cloud-status">${Cloud.configured()?'الإعدادات محفوظة. اضغطي «حفظ واختبار» للتحقق من الاتصال.':'أنشئي مشروع Supabase، شغّلي ملف supabase-schema.sql، ثم ضعي الرابط والمفتاح العام هنا.'}</div></section>`)}
async function saveCloudSettings(){const url=document.getElementById('supabaseUrl')?.value.trim().replace(/\/$/,'')||'',key=document.getElementById('supabaseKey')?.value.trim()||'',autoSync=document.getElementById('autoSync')?.checked!==false;Cloud.saveSettings({provider:'supabase',supabaseUrl:url,supabaseAnonKey:key,autoSync});status('جارٍ اختبار الاتصال...');try{await Cloud.testConnection();sessionStorage.removeItem('novaCloudHydrated');status('تم الاتصال بنجاح. يمكنك الآن تنزيل البيانات أو رفعها.','success')}catch(e){status('تعذر الاتصال: '+e.message,'error')}}
async function pullCloudData(){status('جارٍ تنزيل البيانات...');try{const r=await Cloud.pull();sessionStorage.setItem('novaCloudHydrated','1');status(`تم التنزيل: ${r.channels} قناة، ${r.codes} كود، ${r.devices} جهاز.`,'success');setTimeout(()=>location.reload(),700)}catch(e){status('فشل التنزيل: '+e.message,'error')}}
async function pushCloudData(){if(!confirm('رفع البيانات المحلية الحالية إلى Supabase؟'))return;status('جارٍ رفع البيانات...');try{const r=await Cloud.push();status(`تم الرفع: ${r.channels} قناة، ${r.codes} كود، ${r.devices} جهاز.`,'success')}catch(e){status('فشل الرفع: '+e.message,'error')}}
function disableCloud(){if(!confirm('العودة للوضع المحلي؟ لن تُحذف بيانات Supabase.'))return;Cloud.saveSettings({provider:'local'});sessionStorage.removeItem('novaCloudHydrated');location.reload()}
const observer=new MutationObserver(panel);observer.observe(document.getElementById('adminApp'),{childList:true,subtree:true});panel();
Object.assign(window,{saveCloudSettings,pullCloudData,pushCloudData,disableCloud});
})();