(()=>{
'use strict';
const API=window.NovaAPI,root=document.getElementById('adminApp');
if(!API||!root)return;
const selected=new Set();
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function code(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',part=()=>Array.from({length:4},()=>chars[Math.floor(Math.random()*chars.length)]).join('');return `NOVA-${part()}-${part()}`}
function dateAfter(days){const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function download(name,text,type='text/csv;charset=utf-8'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function toggleSelection(id,checked){checked?selected.add(String(id)):selected.delete(String(id));updateBulkBar()}
function selectAllChannels(checked){document.querySelectorAll('.bulk-channel-check').forEach(x=>{x.checked=checked;toggleSelection(x.value,checked)})}
function bulkChannels(action){if(!selected.size)return alert('حددي قناة واحدة على الأقل.');const ids=[...selected],items=API.getChannels();if(action==='delete'&&!confirm(`حذف ${ids.length} قناة؟`))return;ids.forEach(id=>{const c=items.find(x=>String(x.id)===id);if(!c)return;if(action==='delete')API.removeChannel(id);else API.upsertChannel({...c,enabled:action==='enable'?true:action==='disable'?false:c.enabled,featured:action==='feature'?true:action==='unfeature'?false:c.featured})});selected.clear();window.render?.()}
function updateBulkBar(){const bar=document.querySelector('.bulk-bar');if(!bar)return;bar.querySelector('strong').textContent=selected.size;bar.classList.toggle('show',selected.size>0)}
function generateBatchCodes(){const count=Math.min(500,Math.max(1,Number(prompt('كم كود تريدين إنشاءه؟','10')||0)));if(!count)return;const days=Math.max(1,Number(prompt('مدة الأكواد بالأيام؟','30')||30));const maxDevices=Math.max(1,Number(prompt('عدد الأجهزة لكل كود؟','1')||1));const existing=new Set(API.getActivationCodes().map(x=>x.code));for(let i=0;i<count;i++){let value=code();while(existing.has(value))value=code();existing.add(value);API.upsertActivationCode({code:value,expiresAt:dateAfter(days),maxDevices,enabled:true,devices:[]})}window.render?.();alert(`تم إنشاء ${count} كود.`)}
function exportCodesCsv(){const rows=[['code','expires_at','max_devices','enabled','linked_devices'],...API.getActivationCodes().map(c=>[c.code,c.expiresAt||'',c.maxDevices,c.enabled?'yes':'no',(c.devices||[]).length])];download('nova-activation-codes.csv',rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'))}
function enhanceChannels(){const heading=[...document.querySelectorAll('.admin-card h2')].find(x=>x.textContent.includes('إدارة القنوات'));const card=heading?.closest('.admin-card');const table=card?.querySelector('table');if(!table||table.dataset.bulkReady)return;table.dataset.bulkReady='1';const hr=table.tHead?.rows[0];if(hr){const th=document.createElement('th');th.innerHTML='<input type="checkbox" aria-label="تحديد الكل" onchange="selectAllChannels(this.checked)">';hr.insertBefore(th,hr.firstChild)}[...table.tBodies[0]?.rows||[]].forEach(row=>{const edit=[...row.querySelectorAll('button')].find(b=>b.textContent.trim()==='تعديل');const id=edit?.getAttribute('onclick')?.match(/editChannel\(['"](.+?)['"]\)/)?.[1];if(!id)return;const td=document.createElement('td');td.innerHTML=`<input class="bulk-channel-check" type="checkbox" value="${esc(id)}" onchange="toggleSelection(this.value,this.checked)">`;row.insertBefore(td,row.firstChild)});const bar=document.createElement('div');bar.className='bulk-bar';bar.innerHTML='<span>المحدد: <strong>0</strong></span><button onclick="bulkChannels(\'enable\')">تفعيل</button><button onclick="bulkChannels(\'disable\')">إيقاف</button><button onclick="bulkChannels(\'feature\')">تمييز</button><button onclick="bulkChannels(\'unfeature\')">إلغاء التمييز</button><button class="danger" onclick="bulkChannels(\'delete\')">حذف</button>';card.insertBefore(bar,card.querySelector('.table-wrap'))}
function enhanceCodes(){const h=[...document.querySelectorAll('h2')].find(x=>x.textContent.includes('كود تفعيل جديد'));const card=h?.closest('.admin-card');if(!card||card.dataset.batchReady)return;card.dataset.batchReady='1';const actions=document.createElement('div');actions.className='batch-code-actions';actions.innerHTML='<button class="action-btn" type="button" onclick="generateBatchCodes()">إنشاء دفعة أكواد</button><button class="action-btn" type="button" onclick="exportCodesCsv()">تصدير CSV</button>';card.appendChild(actions)}
function version(){document.querySelectorAll('.admin-brand small').forEach(x=>x.textContent='ADMIN 1.4');document.querySelectorAll('.admin-footer').forEach(x=>x.textContent='Nova TV Admin 1.4 · Bulk Operations')}
let pending=false;function enhance(){if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;version();enhanceChannels();enhanceCodes();updateBulkBar()})}
new MutationObserver(enhance).observe(root,{childList:true,subtree:true});
Object.assign(window,{toggleSelection,selectAllChannels,bulkChannels,generateBatchCodes,exportCodesCsv});enhance();
})();