const DEFAULT_CHANNELS=[
{id:1,name:'Nova News',category:'أخبار',icon:'📰',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true,featured:true},
{id:2,name:'Nova Sports 1',category:'رياضة',icon:'⚽',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true,featured:true},
{id:3,name:'Nova Cinema',category:'أفلام',icon:'🎬',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true},
{id:4,name:'Nova Kids',category:'أطفال',icon:'🧸',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true},
{id:5,name:'Nova Documentary',category:'وثائقي',icon:'🌍',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true},
{id:6,name:'Nova Sports 2',category:'رياضة',icon:'🏆',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true}
];
const DEFAULT_CODES=[{code:'NOVA-2026',enabled:true,expiresAt:'2027-12-31',maxDevices:3,devices:[]}];
const allChannels=JSON.parse(localStorage.getItem('novaChannels')||'null')||DEFAULT_CHANNELS;
const channels=allChannels.filter(c=>c.enabled!==false);
const app=document.getElementById('app');
const state={active:'الكل',query:'',favorites:JSON.parse(localStorage.getItem('novaFavorites')||'[]'),recent:JSON.parse(localStorage.getItem('novaRecent')||'[]'),theme:localStorage.getItem('novaTheme')||'dark',hero:0};
const save=()=>{localStorage.setItem('novaFavorites',JSON.stringify(state.favorites));localStorage.setItem('novaRecent',JSON.stringify(state.recent));localStorage.setItem('novaTheme',state.theme)};
function deviceId(){let id=localStorage.getItem('novaDeviceId');if(!id){id='WEB-'+crypto.getRandomValues(new Uint32Array(2)).join('-');localStorage.setItem('novaDeviceId',id)}return id}
function getCodes(){return JSON.parse(localStorage.getItem('novaActivationCodes')||'null')||DEFAULT_CODES}
function currentCode(){const value=localStorage.getItem('novaActiveCode');return getCodes().find(x=>x.code===value)||null}
function validateCode(value){const codes=getCodes(),code=codes.find(x=>x.code===value);if(!code||!code.enabled)return{ok:false,message:'كود التفعيل غير صحيح أو موقوف.'};if(new Date(code.expiresAt+'T23:59:59').getTime()<Date.now())return{ok:false,message:'انتهت صلاحية هذا الكود.'};code.devices=Array.isArray(code.devices)?code.devices:[];const id=deviceId();if(!code.devices.includes(id)&&code.devices.length>=Number(code.maxDevices||1))return{ok:false,message:'وصل هذا الكود إلى الحد الأقصى للأجهزة.'};if(!code.devices.includes(id)){code.devices.push(id);localStorage.setItem('novaActivationCodes',JSON.stringify(codes))}return{ok:true,code}}
function activate(){const value=document.getElementById('code').value.trim().toUpperCase(),msg=document.getElementById('msg'),result=validateCode(value);if(result.ok){localStorage.setItem('novaActivated','1');localStorage.setItem('novaActiveCode',value);renderHome()}else msg.textContent=result.message}
function nav(active='home'){return `<header class="topbar"><div class="brand">Nova <span>TV</span><small>Preview 0.6</small></div><div class="nav"><button class="${active==='home'?'active':''}" onclick="renderHome()">الرئيسية</button><button onclick="focusSearch()">البحث</button><button class="${active==='fav'?'active':''}" onclick="showFavorites()">المفضلة</button><button class="${active==='recent'?'active':''}" onclick="showRecent()">شوهد مؤخرًا</button><button class="${active==='account'?'active':''}" onclick="showAccount()">حسابي</button><button class="${active==='settings'?'active':''}" onclick="showSettings()">الإعدادات</button><a class="ghost link-btn" href="admin.html">الإدارة</a><button onclick="logout()">خروج</button></div></header>`}
function renderActivation(){app.innerHTML=`<main class="activation"><section class="activation-card"><div class="logo-orb">N</div><h1>Nova <span>TV</span></h1><p>منصة مشاهدة حديثة للتلفزيون والجوال</p><input id="code" value="NOVA-2026" placeholder="أدخلي كود التفعيل" onkeydown="if(event.key==='Enter')activate()"><button class="primary" onclick="activate()">دخول</button><div id="msg" class="error"></div><a class="admin-link" href="admin.html">فتح لوحة الإدارة</a></section></main>`}
function filtered(){return channels.filter(c=>(state.active==='الكل'||c.category===state.active)&&(c.name.toLowerCase().includes(state.query.toLowerCase())||c.category.includes(state.query)))}
function toggleFavorite(id,event){event?.stopPropagation();state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();renderHome()}
function addRecent(id){state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,12);save()}
function play(id){const c=channels.find(x=>x.id===id);if(!c)return;addRecent(id);app.innerHTML=`<div class="shell ${state.theme}">${nav()}<main class="player-wrap"><div class="player-box"><video id="novaPlayer" controls autoplay playsinline src="${c.url}"></video><div id="playerError" class="player-error"></div></div><div class="player-info"><div><span class="live-pill">مباشر</span><h2>${c.name}</h2><p class="meta">${c.category} · بث تجريبي مصرح للاختبار</p></div><div class="player-actions"><button class="ghost" onclick="retryPlayer()">↻ إعادة المحاولة</button><button class="ghost" onclick="toggleFavorite(${c.id},event)">${state.favorites.includes(c.id)?'★ في المفضلة':'☆ إضافة للمفضلة'}</button></div></div></main></div>`;const v=document.getElementById('novaPlayer');v.onerror=()=>document.getElementById('playerError').innerHTML='تعذر تشغيل هذا المصدر.<button class="primary" onclick="retryPlayer()">حاولي مجددًا</button>'}
function retryPlayer(){const v=document.getElementById('novaPlayer');if(v){document.getElementById('playerError').textContent='';v.load();v.play().catch(()=>{})}}
function channelCard(c){return `<article class="card tv-focus" tabindex="0" onclick="play(${c.id})" onkeydown="if(event.key==='Enter')play(${c.id})"><div class="poster"><span>${c.icon}</span><div class="live-badge">LIVE</div></div><div class="card-body"><div class="card-title">${c.name}</div><div class="meta">${c.category}</div><button class="ghost favorite-btn" onclick="toggleFavorite(${c.id},event)">${state.favorites.includes(c.id)?'★ إزالة':'☆ مفضلة'}</button></div></article>`}
function row(title,list){if(!list.length)return'';return `<section class="content-row"><div class="row-head"><h2>${title}</h2><span>${list.length} قناة</span></div><div class="rail">${list.map(channelCard).join('')}</div></section>`}
function renderHome(){const categories=['الكل',...new Set(channels.map(c=>c.category))],featured=channels.filter(c=>c.featured),hero=featured[state.hero%Math.max(featured.length,1)]||channels[0],recent=state.recent.map(id=>channels.find(c=>c.id===id)).filter(Boolean);app.innerHTML=`<div class="shell ${state.theme}">${nav('home')}<section class="cinema-hero"><div class="hero-copy"><span class="eyebrow">NOVA ORIGINAL</span><h1>${hero?.name||'Nova TV'}</h1><p>واجهة مصممة للتلفزيون والريموت، مع وصول سريع للقنوات والمفضلة وسجل المشاهدة.</p><div class="hero-actions"><button class="primary" onclick="play(${hero?.id||1})">▶ ابدأ المشاهدة</button><button class="ghost" onclick="showAccount()">تفاصيل الاشتراك</button></div></div><div class="hero-art">${hero?.icon||'📺'}</div></section><section class="quickbar"><div><strong>${channels.length}</strong><span>قنوات</span></div><div><strong>${new Set(channels.map(c=>c.category)).size}</strong><span>تصنيفات</span></div><div><strong>${state.favorites.length}</strong><span>مفضلة</span></div><div><strong>${state.recent.length}</strong><span>شوهد مؤخرًا</span></div></section><section class="discover"><div class="section-head"><h2>استكشف القنوات</h2><input class="search" placeholder="ابحثي عن قناة" value="${state.query}" oninput="state.query=this.value;renderHome()"></div><div class="chips">${categories.map(cat=>`<button class="chip ${state.active===cat?'active':''}" onclick="state.active='${cat}';renderHome()">${cat}</button>`).join('')}</div></section>${state.query||state.active!=='الكل'?row('نتائج البحث',filtered()):`${row('القنوات المميزة',featured)}${row('شوهد مؤخرًا',recent)}${[...new Set(channels.map(c=>c.category))].map(cat=>row(cat,channels.filter(c=>c.category===cat))).join('')}`}<footer>Nova TV Preview 0.6 · استخدمي فقط مصادر بث تملكين حق استخدامها</footer></div>`;wireRemote()}
function showFavorites(){renderCollection('المفضلة',channels.filter(c=>state.favorites.includes(c.id)),'fav')}
function showRecent(){renderCollection('شوهد مؤخرًا',state.recent.map(id=>channels.find(c=>c.id===id)).filter(Boolean),'recent')}
function renderCollection(title,list,active){app.innerHTML=`<div class="shell ${state.theme}">${nav(active)}<main class="page"><div class="page-title"><h1>${title}</h1><p>إدارة سريعة من أي جهاز.</p></div><div class="grid">${list.length?list.map(channelCard).join(''):'<div class="empty">لا توجد عناصر بعد.</div>'}</div></main></div>`;wireRemote()}
function showAccount(){const code=currentCode();const used=code?.devices?.length||0;app.innerHTML=`<div class="shell ${state.theme}">${nav('account')}<main class="page"><div class="page-title"><h1>حسابي</h1><p>تفاصيل الاشتراك والجهاز.</p></div><div class="account-grid"><section class="panel account-card"><span class="status online">اشتراك فعال</span><h2>Nova Premium</h2><p>الكود: ${code?.code||'—'}</p><div class="account-stat"><span>تاريخ الانتهاء</span><strong>${code?.expiresAt||'—'}</strong></div><div class="account-stat"><span>الأجهزة</span><strong>${used} من ${code?.maxDevices||1}</strong></div><div class="account-stat"><span>معرف هذا الجهاز</span><strong>${deviceId()}</strong></div></section><section class="panel"><h2>ملخص الاستخدام</h2><div class="summary-list"><div><span>المفضلة</span><strong>${state.favorites.length}</strong></div><div><span>شوهد مؤخرًا</span><strong>${state.recent.length}</strong></div><div><span>التصنيفات</span><strong>${new Set(channels.map(c=>c.category)).size}</strong></div></div></section></div></main></div>`}
function showSettings(){app.innerHTML=`<div class="shell ${state.theme}">${nav('settings')}<main class="page"><div class="page-title"><h1>الإعدادات</h1><p>تحكم في تجربة العرض.</p></div><section class="panel settings-list"><button onclick="toggleTheme()"><span>المظهر</span><strong>${state.theme==='dark'?'ليلي':'فاتح'}</strong></button><button onclick="clearRecent()"><span>مسح سجل المشاهدة</span><strong>تنفيذ</strong></button><button onclick="unlinkDevice()"><span>إلغاء ربط هذا الجهاز</span><strong>تنفيذ</strong></button><button onclick="resetPreview()"><span>إعادة ضبط النسخة التجريبية</span><strong>إعادة</strong></button></section></main></div>`}
function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';save();showSettings()}
function clearRecent(){state.recent=[];save();showSettings()}
function unlinkDevice(){const active=localStorage.getItem('novaActiveCode'),codes=getCodes(),item=codes.find(x=>x.code===active);if(item)item.devices=(item.devices||[]).filter(x=>x!==deviceId());localStorage.setItem('novaActivationCodes',JSON.stringify(codes));logout()}
function resetPreview(){localStorage.removeItem('novaFavorites');localStorage.removeItem('novaRecent');state.favorites=[];state.recent=[];showSettings()}
function focusSearch(){renderHome();setTimeout(()=>document.querySelector('.search')?.focus(),30)}
function logout(){localStorage.removeItem('novaActivated');localStorage.removeItem('novaActiveCode');renderActivation()}
function wireRemote(){const items=[...document.querySelectorAll('button,a,input,[tabindex="0"]')];items.forEach((el,i)=>{el.dataset.focusIndex=i});document.onkeydown=e=>{const current=document.activeElement;let i=Number(current?.dataset?.focusIndex??-1);if(['ArrowLeft','ArrowDown'].includes(e.key))i=Math.min(items.length-1,i+1);else if(['ArrowRight','ArrowUp'].includes(e.key))i=Math.max(0,i-1);else return;items[i]?.focus();items[i]?.scrollIntoView({block:'nearest',inline:'nearest'});e.preventDefault()}}
Object.assign(window,{activate,renderHome,play,toggleFavorite,showFavorites,showRecent,showAccount,showSettings,retryPlayer,toggleTheme,clearRecent,unlinkDevice,resetPreview,focusSearch,logout});
if(localStorage.getItem('novaActivated')){const code=currentCode();const result=code?validateCode(code.code):{ok:false};result.ok?renderHome():logout()}else renderActivation();