const DEFAULT_CHANNELS=[
{id:1,name:'Nova News',category:'أخبار',icon:'📰',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true,featured:true,description:'تغطية إخبارية متواصلة على مدار الساعة.'},
{id:2,name:'Nova Sports 1',category:'رياضة',icon:'⚽',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true,featured:true,description:'مباريات وبرامج رياضية مباشرة.'},
{id:3,name:'Nova Cinema',category:'أفلام',icon:'🎬',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true,featured:true,description:'أفلام مختارة وتجربة سينمائية مميزة.'},
{id:4,name:'Nova Kids',category:'أطفال',icon:'🧸',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true,description:'محتوى عائلي آمن وممتع.'},
{id:5,name:'Nova Documentary',category:'وثائقي',icon:'🌍',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true,description:'قصص وثائقية من حول العالم.'},
{id:6,name:'Nova Sports 2',category:'رياضة',icon:'🏆',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true,description:'بطولات وتحليلات رياضية.'}
];
const DEFAULT_CODES=[{code:'NOVA-2026',enabled:true,expiresAt:'2027-12-31',maxDevices:3,devices:[]}];
const app=document.getElementById('app');
let hls=null;
const deviceId=localStorage.getItem('novaDeviceId')||(()=>{const id='NV-'+Math.random().toString(36).slice(2,10).toUpperCase();localStorage.setItem('novaDeviceId',id);return id})();
const state={
 active:'الكل',query:'',hero:0,theme:localStorage.getItem('novaTheme')||'dark',
 favorites:JSON.parse(localStorage.getItem('novaFavorites')||'[]'),
 recent:JSON.parse(localStorage.getItem('novaRecent')||'[]'),
 activation:JSON.parse(localStorage.getItem('novaActivation')||'null')
};
function channels(){return (JSON.parse(localStorage.getItem('novaChannels')||'null')||DEFAULT_CHANNELS).filter(c=>c.enabled!==false)}
function codes(){return JSON.parse(localStorage.getItem('novaActivationCodes')||'null')||DEFAULT_CODES}
function saveState(){localStorage.setItem('novaFavorites',JSON.stringify(state.favorites));localStorage.setItem('novaRecent',JSON.stringify(state.recent));localStorage.setItem('novaTheme',state.theme);if(state.activation)localStorage.setItem('novaActivation',JSON.stringify(state.activation))}
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function validActivation(){if(!state.activation)return false;const item=codes().find(x=>x.code===state.activation.code);return !!item&&item.enabled!==false&&(!item.expiresAt||new Date(item.expiresAt+'T23:59:59')>=new Date())}
function activate(){const input=document.getElementById('code');const msg=document.getElementById('msg');const code=input.value.trim().toUpperCase();const list=codes();const item=list.find(x=>x.code===code);if(!item){msg.textContent='كود التفعيل غير صحيح.';return}if(item.enabled===false){msg.textContent='هذا الكود موقوف.';return}if(item.expiresAt&&new Date(item.expiresAt+'T23:59:59')<new Date()){msg.textContent='انتهت صلاحية هذا الكود.';return}const devices=Array.isArray(item.devices)?item.devices:[];if(!devices.includes(deviceId)&&devices.length>=Number(item.maxDevices||1)){msg.textContent='تم الوصول إلى الحد الأقصى للأجهزة.';return}if(!devices.includes(deviceId)){item.devices=[...devices,deviceId];localStorage.setItem('novaActivationCodes',JSON.stringify(list))}state.activation={code:item.code,expiresAt:item.expiresAt,maxDevices:item.maxDevices,deviceId};saveState();renderHome()}
function renderActivation(){app.innerHTML=`<main class="activation"><section class="activation-card"><div class="logo-orb">N</div><span class="eyebrow">WELCOME TO NOVA</span><h1>Nova <span>TV</span></h1><p>تجربة مشاهدة عصرية على التلفزيون والجوال.</p><label class="activation-label">كود التفعيل<input id="code" value="NOVA-2026" autocomplete="off" onkeydown="if(event.key==='Enter')activate()"></label><button class="primary big" onclick="activate()">تفعيل الجهاز</button><div id="msg" class="error"></div><div class="device-note">معرّف الجهاز: ${deviceId}</div><a class="admin-link" href="admin.html">لوحة الإدارة</a></section></main>`;setTimeout(()=>document.getElementById('code')?.focus(),50)}
function nav(active='home'){return `<header class="topbar"><button class="brand-btn" onclick="renderHome()"><span class="brand-mark">N</span><span class="brand">Nova <b>TV</b><small>SPRINT 1</small></span></button><nav class="nav"><button class="${active==='home'?'active':''}" onclick="renderHome()">الرئيسية</button><button onclick="focusSearch()">البحث</button><button class="${active==='fav'?'active':''}" onclick="showFavorites()">المفضلة</button><button class="${active==='recent'?'active':''}" onclick="showRecent()">المشاهدة الأخيرة</button><button class="${active==='account'?'active':''}" onclick="showAccount()">حسابي</button><button class="${active==='settings'?'active':''}" onclick="showSettings()">الإعدادات</button></nav><button class="profile-button" onclick="showAccount()">NV</button></header>`}
function mobileNav(active='home'){return `<nav class="mobile-nav"><button class="${active==='home'?'active':''}" onclick="renderHome()"><span>⌂</span>الرئيسية</button><button onclick="focusSearch()"><span>⌕</span>البحث</button><button class="${active==='fav'?'active':''}" onclick="showFavorites()"><span>♡</span>المفضلة</button><button class="${active==='account'?'active':''}" onclick="showAccount()"><span>◉</span>حسابي</button></nav>`}
function filtered(){const q=state.query.trim().toLowerCase();return channels().filter(c=>(state.active==='الكل'||c.category===state.active)&&(!q||c.name.toLowerCase().includes(q)||c.category.includes(q)||String(c.description||'').toLowerCase().includes(q)))}
function toggleFavorite(id,event){event?.stopPropagation();state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];saveState();renderHome()}
function addRecent(id){state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,20);saveState()}
function channelCard(c){return `<article class="card tv-focus" tabindex="0" role="button" aria-label="تشغيل ${esc(c.name)}" onclick="play(${c.id})" onkeydown="if(event.key==='Enter')play(${c.id})"><div class="poster"><span>${esc(c.icon||'📺')}</span><div class="poster-glow"></div><div class="live-badge">LIVE</div><button class="heart ${state.favorites.includes(c.id)?'saved':''}" aria-label="المفضلة" onclick="toggleFavorite(${c.id},event)">${state.favorites.includes(c.id)?'♥':'♡'}</button></div><div class="card-body"><div class="card-title">${esc(c.name)}</div><div class="meta">${esc(c.category)} · مباشر</div></div></article>`}
function row(title,list,action=''){if(!list.length)return'';return `<section class="content-row"><div class="row-head"><h2>${title}</h2>${action||`<span>${list.length} قناة</span>`}</div><div class="rail">${list.map(channelCard).join('')}</div></section>`}
function renderHome(){if(!validActivation()){state.activation=null;localStorage.removeItem('novaActivation');renderActivation();return}const all=channels();const categories=['الكل',...new Set(all.map(c=>c.category))];const featured=all.filter(c=>c.featured);const hero=featured[state.hero%Math.max(featured.length,1)]||all[0];const recent=state.recent.map(id=>all.find(c=>c.id===id)).filter(Boolean);const results=filtered();app.innerHTML=`<div class="shell ${state.theme}">${nav('home')}<main><section class="cinema-hero"><div class="hero-overlay"></div><div class="hero-copy"><span class="eyebrow">NOVA PREMIERE</span><h1>${esc(hero?.name||'Nova TV')}</h1><p>${esc(hero?.description||'واجهة مشاهدة سريعة ومريحة مصممة للشاشات الكبيرة والجوال.')}</p><div class="hero-tags"><span>مباشر</span><span>HD</span><span>${esc(hero?.category||'ترفيه')}</span></div><div class="hero-actions"><button class="primary big" onclick="play(${hero?.id||1})">▶ تشغيل الآن</button><button class="glass big" onclick="toggleFavorite(${hero?.id||1},event)">${state.favorites.includes(hero?.id)?'♥ محفوظة':'♡ أضف للمفضلة'}</button></div></div><div class="hero-art"><span>${esc(hero?.icon||'📺')}</span></div><div class="hero-dots">${featured.map((_,i)=>`<button class="${i===state.hero?'active':''}" onclick="state.hero=${i};renderHome()"></button>`).join('')}</div></section><section class="discover"><div class="section-head"><div><span class="eyebrow">اكتشفي المحتوى</span><h2>القنوات المباشرة</h2></div><div class="search-wrap"><span>⌕</span><input id="mainSearch" class="search" placeholder="ابحثي عن قناة أو تصنيف" value="${esc(state.query)}" oninput="state.query=this.value;renderHome()"></div></div><div class="chips">${categories.map(cat=>`<button class="chip ${state.active===cat?'active':''}" onclick="state.active='${esc(cat)}';renderHome()">${esc(cat)}</button>`).join('')}</div></section>${state.query||state.active!=='الكل'?row(`نتائج البحث (${results.length})`,results):`${row('اختيارات Nova',featured)}${row('متابعة المشاهدة',recent)}${[...new Set(all.map(c=>c.category))].map(cat=>row(cat,all.filter(c=>c.category===cat))).join('')}`}<footer>Nova TV · نسخة Sprint 1 · استخدمي فقط مصادر بث تملكين حق استخدامها</footer></main>${mobileNav('home')}</div>`;wireRemote()}
function startVideo(c){const video=document.getElementById('novaPlayer');const error=document.getElementById('playerError');if(!video)return;if(hls){hls.destroy();hls=null}error.textContent='';if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=c.url;video.play().catch(()=>{})}else if(window.Hls&&Hls.isSupported()){hls=new Hls({enableWorker:true,lowLatencyMode:true});hls.loadSource(c.url);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>video.play().catch(()=>{}));hls.on(Hls.Events.ERROR,(_,data)=>{if(data.fatal)error.innerHTML='<span>تعذر تشغيل المصدر.</span><button class="primary" onclick="retryPlayer()">إعادة المحاولة</button>'})}else{video.src=c.url}video.onerror=()=>error.innerHTML='<span>تعذر تشغيل المصدر.</span><button class="primary" onclick="retryPlayer()">إعادة المحاولة</button>'}
function play(id){const c=channels().find(x=>x.id===id);if(!c)return;addRecent(id);app.innerHTML=`<div class="shell ${state.theme} player-page">${nav()}<main class="player-wrap"><button class="back-button" onclick="renderHome()">→ العودة</button><div class="player-box"><video id="novaPlayer" controls autoplay playsinline></video><div id="playerError" class="player-error"></div><div class="channel-watermark">${esc(c.icon||'📺')} ${esc(c.name)}</div></div><div class="player-info"><div><span class="live-pill">● مباشر الآن</span><h1>${esc(c.name)}</h1><p class="meta">${esc(c.description||c.category)}</p></div><div class="player-actions"><button class="glass" onclick="toggleFavorite(${c.id},event)">${state.favorites.includes(c.id)?'♥ في المفضلة':'♡ إضافة للمفضلة'}</button><button class="glass" onclick="fullScreen()">⛶ ملء الشاشة</button><button class="glass" onclick="retryPlayer()">↻ إعادة التحميل</button></div></div>${row('قنوات مشابهة',channels().filter(x=>x.category===c.category&&x.id!==c.id))}</main>${mobileNav()}</div>`;window.currentChannel=c;startVideo(c);wireRemote()}
function retryPlayer(){if(window.currentChannel)startVideo(window.currentChannel)}
function fullScreen(){const box=document.querySelector('.player-box');if(!document.fullscreenElement)box?.requestFullscreen?.();else document.exitFullscreen?.()}
function renderCollection(title,list,active){app.innerHTML=`<div class="shell ${state.theme}">${nav(active)}<main class="page"><div class="page-title"><div><span class="eyebrow">مكتبتك</span><h1>${title}</h1></div><button class="glass" onclick="renderHome()">العودة للرئيسية</button></div><div class="grid">${list.length?list.map(channelCard).join(''):'<div class="empty"><strong>لا توجد عناصر بعد</strong><span>ابدئي بإضافة القنوات التي تحبينها.</span></div>'}</div></main>${mobileNav(active)}</div>`;wireRemote()}
function showFavorites(){const all=channels();renderCollection('المفضلة',all.filter(c=>state.favorites.includes(c.id)),'fav')}
function showRecent(){const all=channels();renderCollection('المشاهدة الأخيرة',state.recent.map(id=>all.find(c=>c.id===id)).filter(Boolean),'recent')}
function showAccount(){const a=state.activation||{};app.innerHTML=`<div class="shell ${state.theme}">${nav('account')}<main class="page"><div class="page-title"><div><span class="eyebrow">الملف الشخصي</span><h1>حسابي</h1></div></div><div class="account-grid"><section class="panel account-card"><div class="account-avatar">NV</div><span class="status online">● الاشتراك فعال</span><h2>Nova Premium</h2><p class="meta">جهازك متصل وجاهز للمشاهدة.</p><div class="account-stat"><span>كود التفعيل</span><strong>${esc(a.code||'-')}</strong></div><div class="account-stat"><span>تاريخ الانتهاء</span><strong>${esc(a.expiresAt||'غير محدد')}</strong></div><div class="account-stat"><span>معرّف الجهاز</span><strong>${esc(deviceId)}</strong></div></section><section class="panel"><h2>ملخص المشاهدة</h2><div class="summary-list"><div><span>القنوات المتاحة</span><strong>${channels().length}</strong></div><div><span>المفضلة</span><strong>${state.favorites.length}</strong></div><div><span>شوهد مؤخرًا</span><strong>${state.recent.length}</strong></div><div><span>نوع الحساب</span><strong>Premium</strong></div></div><button class="danger full" onclick="logout()">تسجيل الخروج من الجهاز</button></section></div></main>${mobileNav('account')}</div>`;wireRemote()}
function showSettings(){app.innerHTML=`<div class="shell ${state.theme}">${nav('settings')}<main class="page narrow"><div class="page-title"><div><span class="eyebrow">التخصيص</span><h1>الإعدادات</h1></div></div><section class="panel settings-list"><button onclick="toggleTheme()"><span><b>المظهر</b><small>تغيير ألوان الواجهة</small></span><strong>${state.theme==='dark'?'ليلي':'فاتح'}</strong></button><button onclick="clearRecent()"><span><b>سجل المشاهدة</b><small>حذف القنوات التي تمت مشاهدتها</small></span><strong>مسح</strong></button><button onclick="clearFavorites()"><span><b>المفضلة</b><small>إزالة جميع القنوات المحفوظة</small></span><strong>مسح</strong></button><button onclick="logout()"><span><b>إلغاء ربط الجهاز</b><small>ستحتاجين إلى إدخال الكود مجددًا</small></span><strong>تنفيذ</strong></button></section></main>${mobileNav()}</div>`;wireRemote()}
function toggleTheme(){state.theme=state.theme==='dark'?'light':'dark';saveState();showSettings()}
function clearRecent(){state.recent=[];saveState();showSettings()}
function clearFavorites(){state.favorites=[];saveState();showSettings()}
function focusSearch(){renderHome();setTimeout(()=>document.getElementById('mainSearch')?.focus(),50)}
function logout(){state.activation=null;localStorage.removeItem('novaActivation');if(hls){hls.destroy();hls=null}renderActivation()}
function wireRemote(){const items=[...document.querySelectorAll('button,a,input,[tabindex="0"]')].filter(x=>x.offsetParent!==null);items.forEach((el,i)=>el.dataset.focusIndex=i);document.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;const current=document.activeElement;let i=Number(current?.dataset?.focusIndex??-1);i+=['ArrowLeft','ArrowDown'].includes(e.key)?1:-1;i=Math.max(0,Math.min(items.length-1,i));items[i]?.focus();items[i]?.scrollIntoView({block:'nearest',inline:'center',behavior:'smooth'});e.preventDefault()}}
Object.assign(window,{state,activate,renderHome,play,toggleFavorite,showFavorites,showRecent,showAccount,showSettings,retryPlayer,fullScreen,toggleTheme,clearRecent,clearFavorites,focusSearch,logout});
validActivation()?renderHome():renderActivation();