const DEFAULT_CHANNELS=[
{id:1,name:'Nova News',category:'أخبار',icon:'📰',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true},
{id:2,name:'Nova Sports 1',category:'رياضة',icon:'⚽',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true},
{id:3,name:'Nova Cinema',category:'أفلام',icon:'🎬',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true},
{id:4,name:'Nova Kids',category:'أطفال',icon:'🧸',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true},
{id:5,name:'Nova Documentary',category:'وثائقي',icon:'🌍',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true},
{id:6,name:'Nova Sports 2',category:'رياضة',icon:'🏆',url:'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',enabled:true}
];
const channels=(JSON.parse(localStorage.getItem('novaChannels')||'null')||DEFAULT_CHANNELS).filter(c=>c.enabled!==false);
const state={active:'الكل',query:'',favorites:JSON.parse(localStorage.getItem('novaFavorites')||'[]'),recent:JSON.parse(localStorage.getItem('novaRecent')||'[]')};
const app=document.getElementById('app');
function save(){localStorage.setItem('novaFavorites',JSON.stringify(state.favorites));localStorage.setItem('novaRecent',JSON.stringify(state.recent.slice(0,8)));}
function activate(){const code=document.getElementById('code').value.trim().toUpperCase();const msg=document.getElementById('msg');if(code==='NOVA-2026'){localStorage.setItem('novaActivated','1');localStorage.setItem('novaCode',code);localStorage.setItem('novaExpiry','2027-12-31');renderHome();}else{msg.textContent='الكود غير صحيح. استخدمي الكود التجريبي NOVA-2026';}}
function renderActivation(){app.innerHTML=`<main class="activation"><section class="activation-card"><div class="logo-orb">N</div><h1>Nova <span>TV</span></h1><p>تجربة مشاهدة حديثة للتلفزيون والجوال</p><input id="code" placeholder="أدخلي كود التفعيل" value="NOVA-2026" onkeydown="if(event.key==='Enter')activate()"><button class="primary" onclick="activate()">دخول</button><div id="msg" class="error"></div><a class="admin-link" href="admin.html">لوحة الإدارة</a></section></main>`;}
function filtered(){return channels.filter(c=>(state.active==='الكل'||c.category===state.active)&&(c.name.toLowerCase().includes(state.query.toLowerCase())||c.category.includes(state.query)));}
function toggleFavorite(id,event){if(event)event.stopPropagation();state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();renderHome();}
function remember(id){state.recent=[id,...state.recent.filter(x=>x!==id)];save();}
function play(id){const c=channels.find(x=>x.id===id);if(!c)return;remember(id);app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand">Nova <span>TV</span></div><button class="ghost" onclick="renderHome()">رجوع</button></header><div class="player-wrap"><div class="player-box"><video id="novaPlayer" controls autoplay playsinline src="${c.url}" onerror="playerError()"></video><div id="playerMessage" class="player-message">جارٍ تحميل البث...</div></div><div class="player-info"><div><h2>${c.name}</h2><p class="meta">${c.category} · بث تجريبي</p></div><div class="player-actions"><button class="ghost" onclick="retryPlayer()">↻ إعادة المحاولة</button><button class="ghost" onclick="toggleFavorite(${c.id},event)">${state.favorites.includes(c.id)?'★ في المفضلة':'☆ إضافة للمفضلة'}</button></div></div></div></div>`;const v=document.getElementById('novaPlayer');v.addEventListener('playing',()=>document.getElementById('playerMessage').style.display='none');}
function playerError(){const m=document.getElementById('playerMessage');if(m){m.style.display='block';m.textContent='تعذر تشغيل البث. تحققي من الرابط أو حاولي مرة أخرى.';}}
function retryPlayer(){const v=document.getElementById('novaPlayer');const m=document.getElementById('playerMessage');if(v){m.style.display='block';m.textContent='جارٍ إعادة المحاولة...';v.load();v.play().catch(playerError);}}
function channelCard(c){return `<article class="card" tabindex="0" onclick="play(${c.id})" onkeydown="if(event.key==='Enter')play(${c.id})"><div class="poster"><span>${c.icon}</span><div class="live-badge">LIVE</div></div><div class="card-body"><div class="card-title">${c.name}</div><div class="meta">${c.category}</div><button class="ghost favorite-btn" onclick="toggleFavorite(${c.id},event)">${state.favorites.includes(c.id)?'★ إزالة':'☆ مفضلة'}</button></div></article>`;}
function renderHome(){const categories=['الكل',...new Set(channels.map(c=>c.category))];const list=filtered();const recent=state.recent.map(id=>channels.find(c=>c.id===id)).filter(Boolean);app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand">Nova <span>TV</span><small>Preview 0.3</small></div><div class="nav"><button class="active">الرئيسية</button><button onclick="document.querySelector('.search').focus()">البحث</button><button onclick="showFavorites()">المفضلة</button><button onclick="showAccount()">حسابي</button><a class="ghost link-btn" href="admin.html">الإدارة</a><button onclick="logout()">خروج</button></div></header><section class="hero"><div class="hero-card"><span class="eyebrow">NOVA ORIGINAL</span><h1>قنواتك في مكان واحد</h1><p>تصميم سريع ومريح للريموت مع بحث فوري، مفضلة، سجل مشاهدة، وحساب اشتراك.</p><button class="primary" onclick="play(${channels[0]?.id||1})">▶ ابدأ المشاهدة</button></div><div class="stats"><div class="stat"><strong>${channels.length}</strong><span>قنوات</span></div><div class="stat"><strong>${new Set(channels.map(c=>c.category)).size}</strong><span>تصنيفات</span></div><div class="stat"><strong>${state.favorites.length}</strong><span>مفضلة</span></div></div></section>${recent.length?`<section class="section"><div class="section-head"><h2>شوهد مؤخرًا</h2></div><div class="grid compact-grid">${recent.slice(0,4).map(channelCard).join('')}</div></section>`:''}<section class="section"><div class="section-head"><h2>القنوات</h2><input class="search" placeholder="ابحثي عن قناة" value="${state.query}" oninput="state.query=this.value;renderHome()"></div><div class="chips">${categories.map(cat=>`<button class="chip ${state.active===cat?'active':''}" onclick="state.active='${cat}';renderHome()">${cat}</button>`).join('')}</div><div class="grid">${list.length?list.map(channelCard).join(''):'<div class="empty">لا توجد نتائج.</div>'}</div></section><footer>Nova TV Preview · استخدمي فقط مصادر بث مصرحًا بها</footer></div>`;}
function showFavorites(){const fav=channels.filter(c=>state.favorites.includes(c.id));app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand">Nova <span>TV</span></div><button class="ghost" onclick="renderHome()">العودة للرئيسية</button></header><section class="section"><h2>المفضلة</h2><div class="grid">${fav.length?fav.map(channelCard).join(''):'<div class="empty">لم تتم إضافة قنوات للمفضلة بعد.</div>'}</div></section></div>`;}
function showAccount(){const code=localStorage.getItem('novaCode')||'NOVA-2026';const expiry=localStorage.getItem('novaExpiry')||'2027-12-31';app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand">Nova <span>TV</span></div><button class="ghost" onclick="renderHome()">العودة للرئيسية</button></header><section class="account-page"><div class="account-card"><div class="account-avatar">N</div><div><h1>الحساب التجريبي</h1><p class="meta">اشتراك Nova TV Preview</p></div></div><div class="account-grid"><div class="info-card"><span>كود التفعيل</span><strong>${code}</strong></div><div class="info-card"><span>حالة الاشتراك</span><strong class="good">نشط</strong></div><div class="info-card"><span>تاريخ الانتهاء</span><strong>${expiry}</strong></div><div class="info-card"><span>عدد المفضلة</span><strong>${state.favorites.length}</strong></div></div><div class="settings-card"><h2>الإعدادات</h2><label><span>تشغيل تلقائي للفيديو</span><input type="checkbox" checked disabled></label><label><span>حفظ المفضلة وسجل المشاهدة</span><input type="checkbox" checked disabled></label><label><span>واجهة مناسبة للتلفزيون</span><input type="checkbox" checked disabled></label><button class="danger" onclick="logout()">تسجيل الخروج</button></div></section></div>`;}
function logout(){localStorage.removeItem('novaActivated');renderActivation();}
window.activate=activate;window.renderHome=renderHome;window.play=play;window.toggleFavorite=toggleFavorite;window.showFavorites=showFavorites;window.showAccount=showAccount;window.logout=logout;window.playerError=playerError;window.retryPlayer=retryPlayer;
localStorage.getItem('novaActivated')?renderHome():renderActivation();