(() => {
'use strict';
const Base=window.NovaUltimate,API=window.NovaAPI;
if(!Base||!API)return;
const state={view:'home',query:'',category:'الكل',country:'الكل',language:'الكل',visible:60,currentChannelId:'',playerTimer:null};
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const idOf=c=>String(c?.id??'');
const channels=()=>API.getChannels({includeDisabled:false})||[];
function category(c){const t=`${c.category||''} ${c.name||''}`.toLowerCase();if(/sport|رياض|football|soccer/.test(t))return'الرياضية';if(/news|أخبار|اخبار/.test(t))return'الأخبار';if(/kid|child|أطفال|اطفال|عائلي|family/.test(t))return'الأطفال';if(/movie|film|cinema|أفلام|افلام/.test(t))return'الأفلام';if(/document|وثائ/.test(t))return'الوثائقية';if(/music|موسيق/.test(t))return'الموسيقى';if(/econom|business|اقتصاد/.test(t))return'الاقتصاد';return'الترفيه'}
function accent(c){return({'الرياضية':'#2469e8','الأخبار':'#d62f3a','الأطفال':'#2ba66d','الأفلام':'#e06b18','الوثائقية':'#159888','الموسيقى':'#8b35df','الاقتصاد':'#3c65c9','الترفيه':'#7736d9'})[category(c)]||'#7139db'}
function icon(c){return({'الرياضية':'⚽','الأخبار':'▤','الأطفال':'☺','الأفلام':'▣','الوثائقية':'◎','الموسيقى':'♫','الاقتصاد':'▥','الترفيه':'★'})[category(c)]||'▶'}
function broken(){try{return JSON.parse(localStorage.getItem('novaBrokenChannels')||'{}')}catch{return{}}}
function saveBroken(m){localStorage.setItem('novaBrokenChannels',JSON.stringify(m))}
function fail(id){const m=broken(),k=String(id),v=m[k]||{count:0,lastAt:0};m[k]={count:v.count+1,lastAt:Date.now()};saveBroken(m)}
function success(id){const m=broken();if(m[String(id)]){delete m[String(id)];saveBroken(m)}}
function hidden(c){const x=broken()[idOf(c)];return!!(x&&x.count>=3&&Date.now()-Number(x.lastAt||0)<86400000)}
function options(values,active){return values.map(v=>`<option value="${esc(v)}" ${v===active?'selected':''}>${esc(v)}</option>`).join('')}
function card(c){const logo=c.logoUrl?`<img src="${esc(c.logoUrl)}" alt="${esc(c.name)}" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span hidden>${icon(c)}</span>`:`<span>${icon(c)}</span>`;return`<article class="s2-channel-card" tabindex="0" onclick="NovaUltimate.openPlayer('${esc(idOf(c))}')"><div class="s2-channel-art" style="--accent:${accent(c)}">${logo}<i>مباشر</i></div><div class="s2-channel-copy"><strong>${esc(c.name)}</strong><span>${esc(category(c))}${c.country?` · ${esc(c.country)}`:''}</span><small>${c.language?esc(c.language):'بث مباشر'}</small></div><button class="s2-favorite" onclick="event.stopPropagation();NovaUltimate.toggleFavorite('${esc(idOf(c))}')">♡</button></article>`}
function filtered(){const q=state.query.trim().toLowerCase();return channels().filter(c=>{if(hidden(c))return false;const co=String(c.country||'').trim()||'غير محدد',la=String(c.language||'').trim()||'غير محدد',hay=`${c.name||''} ${c.category||''} ${co} ${la}`.toLowerCase();return(state.category==='الكل'||category(c)===state.category)&&(state.country==='الكل'||co===state.country)&&(state.language==='الكل'||la===state.language)&&(!q||hay.includes(q))})}
function enhanceChannels(focus=false){const main=document.querySelector('.ultimate-main');if(!main||state.view!=='channels')return;const all=channels(),countries=['الكل',...new Set(all.map(c=>String(c.country||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ar')),languages=['الكل',...new Set(all.map(c=>String(c.language||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ar')),cats=['الكل','الأطفال','الترفيه','الأخبار','الرياضية','الأفلام','الوثائقية','الموسيقى','الاقتصاد'],result=filtered(),visible=result.slice(0,state.visible);main.innerHTML=`<section class="ultimate-page-head s2-page-head"><div><small>المصادر العامة والمضافة</small><h1>القنوات</h1></div><button class="s2-source-button" onclick="NovaSprint2.openSources()">＋ إدارة المصادر</button></section><div class="s2-search-row"><label class="ultimate-search-box"><span>⌕</span><input id="s2Search" value="${esc(state.query)}" placeholder="ابحث عن قناة أو دولة أو لغة" oninput="NovaSprint2.search(this.value)"></label><select onchange="NovaSprint2.setCountry(this.value)">${options(countries,state.country)}</select><select onchange="NovaSprint2.setLanguage(this.value)">${options(languages,state.language)}</select></div><div class="s2-tabs">${cats.map(x=>`<button class="${state.category===x?'active':''}" onclick="NovaSprint2.setCategory('${x}')">${x==='الكل'?'كل القنوات':x}</button>`).join('')}</div><div class="s2-result-summary"><strong>${result.length}</strong> قناة متاحة <span>· تم إخفاء ${all.filter(hidden).length} قناة متعثرة مؤقتًا</span></div><section class="s2-channel-grid">${visible.length?visible.map(card).join(''):'<div class="ultimate-empty">لا توجد نتائج مطابقة.</div>'}</section>${result.length>visible.length?`<button class="s2-load-more" onclick="NovaSprint2.loadMore()">عرض المزيد (${result.length-visible.length})</button>`:''}`;if(focus)setTimeout(()=>document.getElementById('s2Search')?.focus(),30)}
function sourcesPage(){const pub=API.getPublicSources?.()||[],custom=API.getCustomSources?.()||[],h=channels().filter(hidden).length;return`<div class="ultimate-app dark"><header class="s2-manager-head"><button onclick="NovaUltimate.render('account')">← العودة</button><h1>إدارة المصادر</h1><button onclick="NovaSprint2.refreshSources()">↻ تحديث الكل</button></header><main class="s2-manager-main"><section class="s2-source-stats"><div><strong>${pub.length}</strong><span>مصدر عام</span></div><div><strong>${custom.length}</strong><span>مصدر مضاف</span></div><div><strong>${channels().length}</strong><span>قناة محفوظة</span></div><div><strong>${h}</strong><span>متعثر مؤقتًا</span></div></section><section class="s2-manager-grid"><div class="s2-source-panel"><h2>إضافة رابط M3U</h2><p>أضف فقط قائمة تملك حق استخدامها أو تحتوي بثًا عامًا مجانيًا.</p><input id="s2SourceName" placeholder="اسم المصدر"><input id="s2SourceUrl" type="url" placeholder="https://example.com/list.m3u"><button class="ultimate-primary" onclick="NovaSprint2.addSource()">إضافة وتحديث</button><div id="s2SourceMessage" class="s2-message"></div></div><div class="s2-source-panel"><h2>استيراد ملف M3U</h2><p>تُحفظ القنوات داخل هذا الجهاز وتُدمج دون تكرار الروابط.</p><input id="s2File" type="file" accept=".m3u,.m3u8,text/plain,application/x-mpegURL"><button class="ultimate-primary" onclick="NovaSprint2.importFile()">استيراد الملف</button><button class="s2-secondary" onclick="NovaSprint2.resetFailures()">إظهار القنوات المتعثرة مجددًا</button></div></section><section class="s2-source-list"><h2>المصادر المضافة</h2>${custom.length?custom.map(s=>`<article><div><strong>${esc(s.name)}</strong><small>${esc(s.url)}</small></div><button onclick="NovaSprint2.removeSource('${esc(s.id)}')">حذف</button></article>`).join(''):'<div class="ultimate-empty">لا توجد مصادر مخصصة بعد.</div>'}</section></main></div>`}
function enhanceAccount(){const p=document.querySelector('.ultimate-settings-panel');if(!p||p.querySelector('.s2-manage-row'))return;const b=document.createElement('button');b.className='ultimate-setting-row s2-manage-row';b.innerHTML='<span><b>إدارة مصادر القنوات</b><small>إضافة رابط أو ملف M3U وتحديث المصادر</small></span><strong>فتح ›</strong>';b.onclick=openSources;p.appendChild(b)}
function enhance(view=state.view,focus=false){state.view=view;if(view==='channels')enhanceChannels(focus);if(view==='account')enhanceAccount()}
function render(view='home',focus=false){state.view=view;if(view!=='channels'){state.visible=60;state.query=''}Base.render(view,focus);setTimeout(()=>enhance(view,focus),0)}
function search(v){state.query=v;state.visible=60;enhanceChannels();requestAnimationFrame(()=>{const i=document.getElementById('s2Search');i?.focus();if(i)i.setSelectionRange(i.value.length,i.value.length)})}
function setCategory(v){state.category=v;state.visible=60;enhanceChannels()}
function setCountry(v){state.country=v;state.visible=60;enhanceChannels()}
function setLanguage(v){state.language=v;state.visible=60;enhanceChannels()}
function loadMore(){state.visible+=60;enhanceChannels()}
function openSources(){state.view='sources';document.getElementById('app').innerHTML=sourcesPage()}
async function addSource(){const n=document.getElementById('s2SourceName')?.value.trim(),u=document.getElementById('s2SourceUrl')?.value.trim(),m=document.getElementById('s2SourceMessage');try{API.addCustomSource(n||'قائمة خاصة',u);if(m)m.textContent='تمت إضافة المصدر، جارٍ تحميل القنوات…';const r=await API.refreshPublicChannels(true);if(m)m.textContent=r?.ok?`تم تحديث ${r.count} قناة.`:'أُضيف المصدر لكن تعذر تحميله الآن.';setTimeout(openSources,700)}catch{if(m)m.textContent='تحقق من الرابط؛ يجب أن يبدأ بـ http أو https.'}}
async function removeSource(id){API.removeCustomSource(id);await API.refreshPublicChannels(true).catch(()=>{});openSources()}
async function importFile(){const f=document.getElementById('s2File')?.files?.[0];if(!f)return;const r=await API.importM3uText(f.name,await f.text());alert(`تم استيراد ${r.count||0} قناة من الملف.`);openSources()}
async function refreshSources(){const b=document.querySelector('.s2-manager-head button:last-child');if(b){b.disabled=true;b.textContent='جارٍ التحديث…'}await API.refreshPublicChannels(true).catch(()=>null);openSources()}
function resetFailures(){localStorage.removeItem('novaBrokenChannels');openSources()}
function errorActions(){const e=document.getElementById('ultimatePlayerError');if(e)e.innerHTML='<b>تعذر تشغيل هذا المصدر.</b><div><button onclick="NovaSprint2.retryPlayer()">إعادة المحاولة</button><button onclick="NovaSprint2.playAlternative()">قناة بديلة</button><button onclick="NovaUltimate.render(\'channels\')">اختيار قناة</button></div>'}
function monitor(id){clearTimeout(state.playerTimer);state.currentChannelId=String(id);const v=document.getElementById('ultimateVideo');if(!v)return;let ok=false;const good=()=>{ok=true;success(id);document.querySelector('.ultimate-player-placeholder')?.classList.add('hidden')},bad=()=>{if(ok)return;fail(id);errorActions()};v.addEventListener('playing',good,{once:true});v.addEventListener('canplay',good,{once:true});v.addEventListener('error',bad,{once:true});v.addEventListener('stalled',()=>setTimeout(()=>{if(!ok&&v.readyState<3)bad()},7000),{once:true});state.playerTimer=setTimeout(()=>{if(!ok&&v.readyState<3)bad()},15000);const f=document.querySelector('.ultimate-player-controls');if(f&&!f.querySelector('.s2-player-actions')){const d=document.createElement('div');d.className='s2-player-actions';d.innerHTML='<button onclick="NovaSprint2.retryPlayer()">↻ إعادة</button><button onclick="NovaSprint2.playAlternative()">⇥ بديل</button>';f.appendChild(d)}}
function openPlayer(id){Base.openPlayer(id);setTimeout(()=>monitor(id),0)}
function retryPlayer(){if(!state.currentChannelId)return;Base.openPlayer(state.currentChannelId);setTimeout(()=>monitor(state.currentChannelId),0)}
function playAlternative(){const all=channels().filter(c=>!hidden(c)),cur=all.find(c=>idOf(c)===state.currentChannelId);if(!all.length)return render('channels');const same=all.filter(c=>idOf(c)!==state.currentChannelId&&category(c)===category(cur||{})),pool=same.length?same:all.filter(c=>idOf(c)!==state.currentChannelId),next=pool[0];if(!next)return render('channels');Base.openPlayer(idOf(next));setTimeout(()=>monitor(idOf(next)),0)}
window.NovaUltimate=Object.freeze({...Base,render,openPlayer});
window.NovaSprint2=Object.freeze({search,setCategory,setCountry,setLanguage,loadMore,openSources,addSource,removeSource,importFile,refreshSources,resetFailures,retryPlayer,playAlternative});
setTimeout(()=>enhance(state.view),20);
})();